# Nom du projet
name: 'atelier3'
version: '1.0.0'

# Profil dbt à utiliser pour ce projet (doit correspondre au fichier profiles.yml)
profile: 'atelier3'

# Chemins vers les fichiers spécifiques du projet
model-paths: ["models"]         # Répertoire pour les modèles SQL
analysis-paths: ["analyses"]    # Répertoire pour les analyses
test-paths: ["tests"]           # Répertoire pour les tests
seed-paths: ["seeds"]           # Répertoire pour les fichiers seed
macro-paths: ["macros"]         # Répertoire pour les macros
snapshot-paths: ["snapshots"]   # Répertoire pour les snapshots

clean-targets:                  # Répertoires nettoyés par `dbt clean`
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  atelier3:
    # Configuration par défaut pour tous les modèles
    +materialized: table        # Les modèles sont matérialisés en tables par défaut
    +schema: raw                # Schéma par défaut pour tous les modèles dans `raw`

    # Configuration pour le sous-dossier cleansed
    cleansed:
      +schema: cleansed         # Les modèles cleansed iront dans le schéma cleansed
      +materialized: table      # Les modèles cleansed seront matérialisés en tables

    # Configuration pour le sous-d
